### ISSUE TITLE
file too large and NVS error

### ISSUE THREAD

**Issue by skyladle** [lbernstone/setCerts#1]
while I run the code , get below two wrong message , file too large and NVS error: 4354
finally I can not link to AWS Iot. But I am quite sure my key of CA,certificate and private are 100% correct.
these 3 keys on MQTT.fx 1.4.2 is running correctly successful talk with amazon mqtt.
what is wrong thing I done, please advise.
thanks a lot

debug information
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 3
*WM: IP Address:
*WM: 10.1.8.125
10.1.8.125
File Upload: root_cert
Certificate file too large
File Upload: cert_key

<br>mqtt_addr:  xxxxxxxxxxxxxxxxxxx.amazonaws.com
NVS Error: 4354
<br>root_cert:  xxxxxxxxxxxxxxxxxxxxxxxxxx (md5)
NVS Error: 4354

**Comment by skyladle** [comment]
Hi,
I check the file size of my orignal certs through windows file manager
root_ca = 1758
private= 1679
certificate =1220 , seems all small than Key_max_size=1984
but 
I print the file size of root_cert & client_cert & cert_key as below 
Files Upload: root_cert
2048
Certificate file too large
3163
Certificate file too large
0
Files Upload: cert_key
1679
Set NVS Error: 4357

these made me mess , how come size upload from browser is different from orignal
and Waht NVS error 4357 & 4354 stand for.
need somebody help me

**Comment by everslick** [comment]
totalSize in the Upload object should nevertheless never get bigger then what the file really is. when you write the files to SPIFFS instead of NVS, what's their size then?

**Comment by skyladle** [comment]
CA key size =1758 Byte
certificate key size =1224 Byte
private key size = 1679 bytes
then the debug information as below
Content-Length from browser = 5468 Bytes
then it is weird show below  Start file start  but certificate file too large, then the next coming upload certificate file missing.

Start File: symtec_G5_CA.pem Type: application/octet-stream
**File Upload: root_cert
Certificate file too large
Certificate file too large
End File: symtec_G5_CA.pem Type: application/octet-stream Size: 3165**


debug info

method: POST url: /test search: 
headerName: Host
headerValue: 10.1.8.100
headerName: Connection
headerValue: keep-alive
headerName: Content-Length
headerValue: 5468
headerName: Cache-Control
headerValue: max-age=0
headerName: Origin
headerValue: http://10.1.8.100
headerName: Upgrade-Insecure-Requests
headerValue: 1
headerName: Content-Type
headerValue: multipart/form-data; boundary=----WebKitFormBoundaryhHyQui8m0GGRTGiS
headerName: User-Agent
headerValue: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
headerName: Accept
headerValue: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
headerName: Referer
headerValue: http://10.1.8.100/
headerName: Accept-Encoding
headerValue: gzip, deflate
headerName: Accept-Language
headerValue: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7
args: 
Parse Form: Boundary: ----WebKitFormBoundaryhHyQui8m0GGRTGiS Length: 5468
PostArg Name: mqtt_id
PostArg Type: text/plain
PostArg Value: xxxxxxxxxxxxxx

PostArg Name: mqtt_addr
PostArg Type: text/plain
PostArg Value: xxxxxxxxxxxxxxxxxx.amazonaws.com

PostArg FileName: symtec_G5_CA.pem
PostArg Name: root_cert
PostArg Type: application/octet-stream
Start File: symtec_G5_CA.pem Type: application/octet-stream
**File Upload: root_cert
Certificate file too large
Certificate file too large
End File: symtec_G5_CA.pem Type: application/octet-stream Size: 3165**
PostArg FileName:--------------private.pem.key

I download the CA from AWS symantec as below

![aws_symantec](https://user-images.githubusercontent.com/31200783/38542552-afd004f8-3cd4-11e8-809d-133289220fa3.png)

**Comment by skyladle** [comment]
not a issue of this code
